# Settings 部分
Settings:
  DEV: False                            # 开发者模式，默认为 False

# Alist to Strm 任务列表
Alist2StrmList:
  - id: 国产剧                            # 标识 ID
    cron: 0 1 * * * # 定时任务表达式 (每日凌晨 1:00)
    url: http://154.12.61.104:10010          # Alist 服务器地址
    username: admin                     # Alist 用户名
    password: Shuonoopenlist1791..      # Alist 密码
    source_dir: /123云盘/Video/TV/国产剧  # Alist 服务器上的源文件夹路径
    target_dir: /Users/yuanjing/Code/AutoFilm/test # strm 文件输出路径
    flatten_mode: False                 # 平铺模式，默认为 False
    subtitle: True                      # 下载字幕文件
    image: False                        # 不下载图片文件
    nfo: True                           # 下载 .nfo 文件
    mode: RawURL                    # Strm 文件中的内容（可选项：AlistURL、RawURL、AlistPath）
    overwrite: False                  # 覆盖模式，本地路径存在同名文件时是否重新生成/下载该文件（可选，默认 False）
    sync_server: True                 # 是否同步服务器（可选，默认为 True）
    sync_ignore: \.(nfo|jpg)$         # 同步时忽略的文件正则表达式（可选，默认为空，仅对文件名及拓展名有效，对路径无效）
    other_ext:                        # 自定义下载后缀，使用西文半角逗号进行分割，（可选，默认为空）
    max_workers: 50                   # 最大并发数，减轻对 Alist 服务器的负载（可选，默认 50）
    max_downloaders: 5                # 最大同时下载文件数（可选，默认 5）
    wait_time: 0                      # 遍历请求间隔时间，避免被风控，单位为秒，默认为 0
