# Settings 部分
Settings:
  DEV: False                            # 开发者模式，默认为 False

# Alist to Strm 任务列表
Alist2StrmList:
  - id: 国产剧                            # 标识 ID
    cron: 0 1 * * * # 定时任务表达式 (每日凌晨 1:00)
    url: http://openlist:5244          # Alist 服务器地址
    username: admin                     # Alist 用户名
    password: Shuonoopenlist1791..      # Alist 密码
    source_dir: /123云盘/Video/TV/国产剧  # Alist 服务器上的源文件夹路径
    target_dir: /vol1/1000/Share/视频/媒体库/strm/TV/国产剧 # strm 文件输出路径
    flatten_mode: False                 # 平铺模式，默认为 False
    subtitle: True                      # 下载字幕文件
    image: False                        # 不下载图片文件
    nfo: True                           # 下载 .nfo 文件
    mode: RawURL                      # Strm 文件中的内容（可选项：AlistURL、RawURL、AlistPath）
    overwrite: False                  # 覆盖模式，本地路径存在同名文件时是否重新生成/下载该文件（可选，默认 False）
    sync_server: True                 # 是否同步服务器（可选，默认为 True）
    sync_ignore: \.(nfo|jpg)$         # 同步时忽略的文件正则表达式（可选，默认为空，仅对文件名及拓展名有效，对路径无效）
    other_ext:                        # 自定义下载后缀，使用西文半角逗号进行分割，（可选，默认为空）
    max_workers: 50                   # 最大并发数，减轻对 Alist 服务器的负载（可选，默认 50）
    max_downloaders: 5                # 最大同时下载文件数（可选，默认 5）
    wait_time: 0                      # 遍历请求间隔时间，避免被风控，单位为秒，默认为 0

  - id: 儿童剧
    cron: 0 2 * * * # 定时任务表达式 (每日凌晨 2:00)
    url: http://openlist:5244
    username: admin
    password: Shuonoopenlist1791..
    source_dir: /123云盘/Video/TV/儿童
    target_dir: /vol1/1000/Share/视频/媒体库/strm/TV/儿童剧
    flatten_mode: False
    subtitle: True
    image: False
    nfo: True
    mode: RawURL                    # Strm 文件中的内容（可选项：AlistURL、RawURL、AlistPath）
    overwrite: False                  # 覆盖模式，本地路径存在同名文件时是否重新生成/下载该文件（可选，默认 False）
    sync_server: True                 # 是否同步服务器（可选，默认为 True）
    sync_ignore: \.(nfo|jpg)$         # 同步时忽略的文件正则表达式（可选，默认为空，仅对文件名及拓展名有效，对路径无效）
    other_ext:                        # 自定义下载后缀，使用西文半角逗号进行分割，（可选，默认为空）
    max_workers: 50                   # 最大并发数，减轻对 Alist 服务器的负载（可选，默认 50）
    max_downloaders: 5                # 最大同时下载文件数（可选，默认 5）
    wait_time: 0                      # 遍历请求间隔时间，避免被风控，单位为秒，默认为 0

  - id: 日韩剧
    cron: 0 3 * * * # 定时任务表达式 (每日凌晨 3:00)
    url: http://openlist:5244
    username: admin
    password: Shuonoopenlist1791..
    source_dir: /123云盘/Video/TV/日韩剧
    target_dir: /vol1/1000/Share/视频/媒体库/strm/TV/日韩剧
    flatten_mode: False
    subtitle: True
    image: False
    nfo: True
    mode: RawURL                    # Strm 文件中的内容（可选项：AlistURL、RawURL、AlistPath）
    overwrite: False                  # 覆盖模式，本地路径存在同名文件时是否重新生成/下载该文件（可选，默认 False）
    sync_server: True                 # 是否同步服务器（可选，默认为 True）
    sync_ignore: \.(nfo|jpg)$         # 同步时忽略的文件正则表达式（可选，默认为空，仅对文件名及拓展名有效，对路径无效）
    other_ext:                        # 自定义下载后缀，使用西文半角逗号进行分割，（可选，默认为空）
    max_workers: 50                   # 最大并发数，减轻对 Alist 服务器的负载（可选，默认 50）
    max_downloaders: 5                # 最大同时下载文件数（可选，默认 5）
    wait_time: 0                      # 遍历请求间隔时间，避免被风控，单位为秒，默认为 0

  - id: 欧美剧
    cron: 0 4 * * * # 定时任务表达式 (每日凌晨 4:00)
    url: http://openlist:5244
    username: admin
    password: Shuonoopenlist1791..
    source_dir: /123云盘/Video/TV/欧美剧
    target_dir: /vol1/1000/Share/视频/媒体库/strm/TV/欧美剧
    flatten_mode: False
    subtitle: True
    image: False
    nfo: True
    mode: RawURL                    # Strm 文件中的内容（可选项：AlistURL、RawURL、AlistPath）
    overwrite: False                  # 覆盖模式，本地路径存在同名文件时是否重新生成/下载该文件（可选，默认 False）
    sync_server: True                 # 是否同步服务器（可选，默认为 True）
    sync_ignore: \.(nfo|jpg)$         # 同步时忽略的文件正则表达式（可选，默认为空，仅对文件名及拓展名有效，对路径无效）
    other_ext:                        # 自定义下载后缀，使用西文半角逗号进行分割，（可选，默认为空）
    max_workers: 50                   # 最大并发数，减轻对 Alist 服务器的负载（可选，默认 50）
    max_downloaders: 5                # 最大同时下载文件数（可选，默认 5）
    wait_time: 0                      # 遍历请求间隔时间，避免被风控，单位为秒，默认为 0

  - id: 纪录片
    cron: 0 5 * * * # 定时任务表达式 (每日凌晨 5:00)
    url: http://openlist:5244
    username: admin
    password: Shuonoopenlist1791..
    source_dir: /123云盘/Video/TV/纪录片
    target_dir: /vol1/1000/Share/视频/媒体库/strm/TV/纪录片
    flatten_mode: False
    subtitle: True
    image: False
    nfo: True
    mode: RawURL                    # Strm 文件中的内容（可选项：AlistURL、RawURL、AlistPath）
    overwrite: False                  # 覆盖模式，本地路径存在同名文件时是否重新生成/下载该文件（可选，默认 False）
    sync_server: True                 # 是否同步服务器（可选，默认为 True）
    sync_ignore: \.(nfo|jpg)$         # 同步时忽略的文件正则表达式（可选，默认为空，仅对文件名及拓展名有效，对路径无效）
    other_ext:                        # 自定义下载后缀，使用西文半角逗号进行分割，（可选，默认为空）
    max_workers: 50                   # 最大并发数，减轻对 Alist 服务器的负载（可选，默认 50）
    max_downloaders: 5                # 最大同时下载文件数（可选，默认 5）
    wait_time: 0                      # 遍历请求间隔时间，避免被风控，单位为秒，默认为 0

  - id: 综艺
    cron: 0 6 * * * # 定时任务表达式 (每日早上 6:00)
    url: http://openlist:5244
    username: admin
    password: Shuonoopenlist1791..
    source_dir: /123云盘/Video/TV/综艺
    target_dir: /vol1/1000/Share/视频/媒体库/strm/TV/综艺
    flatten_mode: False
    subtitle: True
    image: False
    nfo: True
    mode: RawURL                    # Strm 文件中的内容（可选项：AlistURL、RawURL、AlistPath）
    overwrite: False                  # 覆盖模式，本地路径存在同名文件时是否重新生成/下载该文件（可选，默认 False）
    sync_server: True                 # 是否同步服务器（可选，默认为 True）
    sync_ignore: \.(nfo|jpg)$         # 同步时忽略的文件正则表达式（可选，默认为空，仅对文件名及拓展名有效，对路径无效）
    other_ext:                        # 自定义下载后缀，使用西文半角逗号进行分割，（可选，默认为空）
    max_workers: 50                   # 最大并发数，减轻对 Alist 服务器的负载（可选，默认 50）
    max_downloaders: 5                # 最大同时下载文件数（可选，默认 5）
    wait_time: 0                      # 遍历请求间隔时间，避免被风控，单位为秒，默认为 0

  - id: 动漫
    cron: 30 1 * * * # 定时任务表达式 (每日凌晨 1:30)
    url: http://openlist:5244
    username: admin
    password: Shuonoopenlist1791..
    source_dir: /123云盘/Video/Animates/动漫
    target_dir: /vol1/1000/Share/视频/媒体库/strm/Animates/动漫
    flatten_mode: False
    subtitle: True
    image: False
    nfo: True
    mode: RawURL                    # Strm 文件中的内容（可选项：AlistURL、RawURL、AlistPath）
    overwrite: False                  # 覆盖模式，本地路径存在同名文件时是否重新生成/下载该文件（可选，默认 False）
    sync_server: True                 # 是否同步服务器（可选，默认为 True）
    sync_ignore: \.(nfo|jpg)$         # 同步时忽略的文件正则表达式（可选，默认为空，仅对文件名及拓展名有效，对路径无效）
    other_ext:                        # 自定义下载后缀，使用西文半角逗号进行分割，（可选，默认为空）
    max_workers: 50                   # 最大并发数，减轻对 Alist 服务器的负载（可选，默认 50）
    max_downloaders: 5                # 最大同时下载文件数（可选，默认 5）
    wait_time: 0                      # 遍历请求间隔时间，避免被风控，单位为秒，默认为 0

  - id: 国漫
    cron: 30 2 * * * # 定时任务表达式 (每日凌晨 2:30)
    url: http://openlist:5244
    username: admin
    password: Shuonoopenlist1791..
    source_dir: /123云盘/Video/Animates/国漫
    target_dir: /vol1/1000/Share/视频/媒体库/strm/Animates/国漫
    flatten_mode: False
    subtitle: True
    image: False
    nfo: True
    mode: RawURL                    # Strm 文件中的内容（可选项：AlistURL、RawURL、AlistPath）
    overwrite: False                  # 覆盖模式，本地路径存在同名文件时是否重新生成/下载该文件（可选，默认 False）
    sync_server: True                 # 是否同步服务器（可选，默认为 True）
    sync_ignore: \.(nfo|jpg)$         # 同步时忽略的文件正则表达式（可选，默认为空，仅对文件名及拓展名有效，对路径无效）
    other_ext:                        # 自定义下载后缀，使用西文半角逗号进行分割，（可选，默认为空）
    max_workers: 50                   # 最大并发数，减轻对 Alist 服务器的负载（可选，默认 50）
    max_downloaders: 5                # 最大同时下载文件数（可选，默认 5）
    wait_time: 0                      # 遍历请求间隔时间，避免被风控，单位为秒，默认为 0

  - id: 外语电影
    cron: 0 7 * * * # 定时任务表达式 (每日早上 7:00)
    url: http://openlist:5244
    username: admin
    password: Shuonoopenlist1791..
    source_dir: /123云盘/Video/Movies/外语电影
    target_dir: /vol1/1000/Share/视频/媒体库/strm/Movies/外语电影
    flatten_mode: False
    subtitle: True
    image: False
    nfo: True
    mode: RawURL                    # Strm 文件中的内容（可选项：AlistURL、RawURL、AlistPath）
    overwrite: False                  # 覆盖模式，本地路径存在同名文件时是否重新生成/下载该文件（可选，默认 False）
    sync_server: True                 # 是否同步服务器（可选，默认为 True）
    sync_ignore: \.(nfo|jpg)$         # 同步时忽略的文件正则表达式（可选，默认为空，仅对文件名及拓展名有效，对路径无效）
    other_ext:                        # 自定义下载后缀，使用西文半角逗号进行分割，（可选，默认为空）
    max_workers: 50                   # 最大并发数，减轻对 Alist 服务器的负载（可选，默认 50）
    max_downloaders: 5                # 最大同时下载文件数（可选，默认 5）
    wait_time: 0                      # 遍历请求间隔时间，避免被风控，单位为秒，默认为 0

  - id: 华语电影
    cron: 30 7 * * * # 定时任务表达式 (每日早上 7:30)
    url: http://openlist:5244
    username: admin
    password: Shuonoopenlist1791..
    source_dir: /123云盘/Video/Movies/华语电影
    target_dir: /vol1/1000/Share/视频/媒体库/strm/Movies/华语电影
    flatten_mode: False
    subtitle: True
    image: False
    nfo: True
    mode: RawURL                    # Strm 文件中的内容（可选项：AlistURL、RawURL、AlistPath）
    overwrite: False                  # 覆盖模式，本地路径存在同名文件时是否重新生成/下载该文件（可选，默认 False）
    sync_server: True                 # 是否同步服务器（可选，默认为 True）
    sync_ignore: \.(nfo|jpg)$         # 同步时忽略的文件正则表达式（可选，默认为空，仅对文件名及拓展名有效，对路径无效）
    other_ext:                        # 自定义下载后缀，使用西文半角逗号进行分割，（可选，默认为空）
    max_workers: 50                   # 最大并发数，减轻对 Alist 服务器的负载（可选，默认 50）
    max_downloaders: 5                # 最大同时下载文件数（可选，默认 5）
    wait_time: 0                      # 遍历请求间隔时间，避免被风控，单位为秒，默认为 0

  - id: 动画电影
    cron: 0 8 * * * # 定时任务表达式 (每日早上 8:00)
    url: http://openlist:5244
    username: admin
    password: Shuonoopenlist1791..
    source_dir: /123云盘/Video/Movies/动画电影
    target_dir: /vol1/1000/Share/视频/媒体库/strm/Movies/动画电影
    flatten_mode: False
    subtitle: True
    image: False
    nfo: True
    mode: RawURL                    # Strm 文件中的内容（可选项：AlistURL、RawURL、AlistPath）
    overwrite: False                  # 覆盖模式，本地路径存在同名文件时是否重新生成/下载该文件（可选，默认 False）
    sync_server: True                 # 是否同步服务器（可选，默认为 True）
    sync_ignore: \.(nfo|jpg)$         # 同步时忽略的文件正则表达式（可选，默认为空，仅对文件名及拓展名有效，对路径无效）
    other_ext:                        # 自定义下载后缀，使用西文半角逗号进行分割，（可选，默认为空）
    max_workers: 50                   # 最大并发数，减轻对 Alist 服务器的负载（可选，默认 50）
    max_downloaders: 5                # 最大同时下载文件数（可选，默认 5）
    wait_time: 0                      # 遍历请求间隔时间，避免被风控，单位为秒，默认为 0
    
  - id: NoSign
    cron: 0 9 * * * # 定时任务表达式 (每日早上 9:00)
    url: http://openlist:5244
    username: admin
    password: Shuonoopenlist1791..
    source_dir: /123云盘/Video/NoSign
    target_dir: /vol1/1000/Share/视频/媒体库/strm/NoSign
    flatten_mode: False
    subtitle: True
    image: False
    nfo: True
    mode: RawURL                    # Strm 文件中的内容（可选项：AlistURL、RawURL、AlistPath）
    overwrite: False                  # 覆盖模式，本地路径存在同名文件时是否重新生成/下载该文件（可选，默认 False）
    sync_server: True                 # 是否同步服务器（可选，默认为 True）
    sync_ignore: \.(nfo|jpg)$         # 同步时忽略的文件正则表达式（可选，默认为空，仅对文件名及拓展名有效，对路径无效）
    other_ext:                        # 自定义下载后缀，使用西文半角逗号进行分割，（可选，默认为空）
    max_workers: 50                   # 最大并发数，减轻对 Alist 服务器的负载（可选，默认 50）
    max_downloaders: 5                # 最大同时下载文件数（可选，默认 5）
    wait_time: 0                      # 遍历请求间隔时间，避免被风控，单位为秒，默认为 0